version: 2
jobs:
  build:
    docker:
      - image: php:7.0-apache
    working_directory: /home/fajob/www
    steps:
      - checkout
      - run:
          name: Install System Packages
          command: |
            apt-get update && apt-get -y install zip
            apt-get --quiet install --yes python-pip
            pip install -U pip
            pip install awscli
      - run:
          name: zip code
          command: | 
            zip -r admin.zip ./admin
            zip -r www.zip ./www
      - run:
          name: Upload code to S3
          command: aws s3 cp admin.zip s3://tst-cd-willgroup/admin.zip
          #command: aws s3 sync /home/ubuntu/ s3://tst-cd-willgroup/hoila.zip
      - deploy:
          name: Execute CodeDeploy
          command: aws deploy create-deployment --application-name admin --deployment-group-name tst-admin-deploygroup --deployment-config-name CodeDeployDefault.AllAtOnce --s3-location bucket=tst-cd-willgroup,bundleType=zip,key=admin.zip --region ap-southeast-1"
